{
 "title": "Prefix History (by Router)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "router", "label": "Router", "query": "select name from routers" }
  ]
 },
 "panels": [
  {
   "title": "Prefix Advertisements & Withdrawals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  interval_time as time,\n  sum(updates) as updates, sum(withdraws) as withdraws\nFROM stats_chg_bypeer s\nWHERE $__timeFilter(interval_time)\n   AND s.peer_hash_id IN (SELECT peer_hash_id\n                            from v_peers\n                            where routername = '$router')\n\ngroup by interval_time\nORDER BY interval_time ASC\n"
    }
   ]
  },
  {
   "title": "Changes by Peer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  interval_time as time,\n  sum(updates) + sum(withdraws) as value,\n  left(PeerName,32) as metric\nFROM stats_chg_bypeer l\n  JOIN v_peers p ON (l.peer_hash_id = p.peer_hash_id)\nWHERE $__timeFilter(interval_time)\n   AND p.routername = '$router'\nGROUP BY l.interval_time,peername\nORDER BY interval_time ASC\n\n"
    }
   ]
  },
  {
   "title": "Prefix History",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": " select lastmodified,event,peername,prefix,\n        origin_as,as_path,communities \n    from v_ip_routes_history \n    where  $__timeFilter(lastmodified)\n      AND routername = '[[router]]'\n    order by lastmodified desc,id desc\n    limit 1000;"
    }
   ]
  }
 ]
}