{
 "title": "BGP Sec: Hijack/Leak (by AS Name)",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "as_name", "label": "AS Name", "query": "${VAR_AS_NAME}" }
  ]
 },
 "panels": [
  {
   "title": "Transit Leak/Hijacks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"prefix\")) FROM \"alerts\"  WHERE (\"tag-type\" = 'TRANSIT_LEAK' OR \"tag-type\" = 'TRANSIT_HIJACK') AND  $timeFilter GROUP BY time($__interval);",
     "rawSql": "SELECT \n  $__timeGroup(timestamp, $__interval),\n  count(message) \nFROM alerts  \nWHERE $__timeFilter(timestamp)\n  AND type in ('TRANSIT_LEAK', 'TRANSIT_HIJACK')\n  and (monitored_asname ilike '%[[as_name]]%' OR offending_asname ilike '%[[as_name]]%')\nGROUP BY time\norder by time\n"
    }
   ]
  },
  {
   "title": "Upstream Leak/Hijacks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"prefix\")) FROM \"alerts\"  WHERE (\"tag-type\" = 'UPSTREAM_LEAK' or \"tag-type\" = 'UPSTREAM_HIJACK') AND  $timeFilter GROUP BY time($__interval);",
     "rawSql": "SELECT \n  $__timeGroup(timestamp, $__interval),\n  count(message) \nFROM alerts  \nWHERE $__timeFilter(timestamp)\n  AND type in ('UPSTREAM_LEAK', 'UPSTREAM_HIJACK')\n  and (monitored_asname ilike '%[[as_name]]%' OR offending_asname ilike '%[[as_name]]%')\nGROUP BY time\norder by time"
    }
   ]
  },
  {
   "title": "Origin HiJacks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"prefix\")) FROM \"alerts\"  WHERE \"tag-type\" = 'ORIGIN_HIJACK' AND  $timeFilter GROUP BY time($__interval);\n",
     "rawSql": "SELECT \n  $__timeGroup(timestamp, $__interval),\n  count(message) \nFROM alerts  \nWHERE $__timeFilter(timestamp)\n  AND type in ('ORIGIN_HIJACK')\n  and (monitored_asname ilike '%[[as_name]]%' OR offending_asname ilike '%[[as_name]]%')\nGROUP BY time\norder by time"
    }
   ]
  },
  {
   "title": "Alert Counts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alerts",
     "query": "select",
     "rawSql": "SELECT\n  $__timeGroup(timestamp, '3m'),\n  count(message) as alerts\nFROM\n  alerts\nWHERE\n  $__timeFilter(timestamp)\n  and (monitored_asname ilike '%[[as_name]]%' OR offending_asname ilike '%[[as_name]]%')\ngroup by time\norder by time\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(timestamp, '3m'),\n  count(monitored_asn) as asns\nFROM\n  alerts\nWHERE\n  $__timeFilter(timestamp)\n  and (monitored_asname ilike '%[[as_name]]%' OR offending_asname ilike '%[[as_name]]%')\ngroup by monitored_asn,time\norder by time\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(timestamp, '3m'),\n  count(affected_prefix) as prefixes\nFROM\n  alerts\nWHERE\n  $__timeFilter(timestamp)\n  and (monitored_asname ilike '%[[as_name]]%' OR offending_asname ilike '%[[as_name]]%')\ngroup by time,affected_prefix\norder by time\n"
    }
   ]
  },
  {
   "title": "Offending ASNs",
   "type": "graph",
   "description": "Count of alerts by offending ASNs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Count of Alerts" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tag-offending_asn" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alerts",
     "query": "SELECT count(\"message\") as items FROM \"10weeks\".\"alerts\" WHERE  $timeFilter GROUP BY time(60s),\"tag-offending_asn\" fill(none) ",
     "rawSql": "SELECT\n  $__timeGroup(timestamp, '3m'),\n  count(message) as value,\n  offending_asn::text as metric\nFROM\n  alerts\nWHERE\n  $__timeFilter(timestamp)\n  and (monitored_asname ilike '%[[as_name]]%' OR offending_asname ilike '%[[as_name]]%')\ngroup by time,offending_asn\norder by time\n",
     "slimit": "25",
     "tags": [
      { "key": "tag-offending_asn", "operator": "<>", "value": "''" }
     ]
    }
   ]
  },
  {
   "title": "Monitored ASNs",
   "type": "graph",
   "description": "Count of alerts by monitored ASNs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Count of Alerts" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tag-offending_asn" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alerts",
     "query": "SELECT count(\"message\") as items FROM \"10weeks\".\"alerts\" WHERE  $timeFilter GROUP BY time(60s),\"tag-monitored_asn\" fill(none) ",
     "rawSql": "SELECT\n  $__timeGroup(timestamp, '3m'),\n  count(message) as value,\n  monitored_asn::text as metric\nFROM\n  alerts\nWHERE\n  $__timeFilter(timestamp)\n  and (monitored_asname ilike '%[[as_name]]%' OR offending_asname ilike '%[[as_name]]%')\ngroup by time,monitored_asn\norder by time\n",
     "slimit": "25",
     "tags": [
      { "key": "tag-offending_asn", "operator": "<>", "value": "''" }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alerts",
     "rawSql": "SELECT\n  timestamp as \"Time\", type, left(monitored_asname,32) as \"Monitored\", left(offending_asname, 32) as \"Offending\", message, history_url as \"History\"\nFROM\n  alerts\nWHERE\n  $__timeFilter(timestamp)\n  and (monitored_asname ilike '%[[as_name]]%' OR offending_asname ilike '%[[as_name]]%')\n"
    }
   ]
  }
 ]
}